$schema: "http://json-schema.org/2020-12/schema#"

description: snakemake configuration file

definitions:
  envmodules_list:
    description: >-
      hpc environment module list
    type: array
    items:
      type: string
    uniqueItems: true




type: object

# possible entries of the config file and which type they should be
properties:
  envmodules:
    type: object
    description: >-
      envmodules listings for relevant rules
    default: {}
    properties:
      FastQC_BeforeTrimming:
        default: []
        $ref: "#/definitions/envmodules_list"
      MultiQC_BeforeTrimming:
        default: []
        $ref: "#/definitions/envmodules_list"
      Cutadapt_Adapter_Trimming:
        default: []
        $ref: "#/definitions/envmodules_list"
      FastQC_AfterTrimming:
        default: []
        $ref: "#/definitions/envmodules_list"
      MultiQC_AfterTrimming:
        default: []
        $ref: "#/definitions/envmodules_list"
      KrakenUniq:
        default: []
        $ref: "#/definitions/envmodules_list"
      KrakenUniq2Krona:
        default: []
        $ref: "#/definitions/envmodules_list"
  illumina_universal_adapter:
    type: string
    description: >-
      Illumina adapter to use for trimming
    default: AGATCGGAAGAG
  krakenuniq_db:
    type: string
    description: >-
      KrakenUniq database
  bowtie2_patho_db:
    type: string
    description: >-
to      Bowtie2 pathogenome database
  samplefile:
    description: >-
      Sample definition file. Tab- or comma-separated values. See
      samples.schema.yaml for a description of file format.
    type: string
    pattern: .+\.(tsv|csv)$
  samples:
    type: object
    default: {}
    properties:
      include:
        description: >-
          Samples to include in analysis. If empty use all samples in
          sampleinfo file
        type: array
        items:
          type: string
        uniqueItems: true
      exclude:
        description: >-
          Samples to exclude from analysis.
        type: array
        items:
          type: string
        uniqueItems: true


# entries that have to be in the config file for successful validation
required:
  - samplefile
