name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches_ignore: []

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint workflow
      uses: snakemake/snakemake-github-action@v1.24.0
      with:
        directory: .
        snakefile: workflow/Snakefile
        args: "--lint"

  Testing:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: Linting
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: cache-conda
      uses: actions/cache@v2
      env:
        CACHE_NUMBER: 0
      with:
        path: .test/.snakemake/conda
        key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('workflow/envs/*.yaml') }}

    - name: Install workflow environments
      uses: snakemake/snakemake-github-action@v1.24.0
      if: steps.cache-conda.outputs.cache-hit != 'true'
      with:
        directory: .test
        snakefile: workflow/Snakefile
        args: "--use-conda --show-failed-logs -j 2 --conda-cleanup-pkgs cache --conda-create-envs-only"

    - name: Build krakenuniq database
      working-directory: .test
      run: |
        env=$(grep krakenuniq .snakemake/conda/*yaml | awk '{print $1}' | sed -e "s/.yaml://g")
        which conda
        source /github/workspace/.conda/etc/profile.d/conda.sh
        conda activate $env
        krakenuniq-build --db resources/KrakenUniq_DB
        conda deactivate

    - name: Build krona taxonomy
      working-directory: .test
      run: |
        env=$(grep krona .snakemake/conda/*yaml | awk '{print $1}' | sed -e "s/.yaml://g")
        $env/opt/krona/updateTaxonomy.sh
    - name: Test workflow (local test data)
      uses: snakemake/snakemake-github-action@v1.24.0
      with:
        directory: .test
        snakefile: workflow/Snakefile
        args: "--show-failed-logs -j 2 --use-conda"
    - name: Test report
      uses: snakemake/snakemake-github-action@v1.24.0
      with:
        directory: .test
        snakefile: workflow/Snakefile
        args: "--report report.zip"
